<?php
require_once(__DIR__ . '/../config/db.php');


if (USE_MOCK_DATA) {
    echo "Inserting mock data...\n";

    $mockStores = [
        [
            'domain' => 'shopifystore1.com',
            'title' => 'Shopify Store One',
            'description' => 'General e-commerce store built on Shopify',
            'language' => 'en',
            'country' => 'US',
            'currency' => 'USD',
            'product_count' => 150,
            'avg_price' => 25.99,
            'categories' => 'Fashion, Accessories',
            'tech_stack' => 'Shopify',
            'shipping_destinations' => 'US, CA, UK',
            'payment_methods' => 'Visa, Mastercard, PayPal',
            'contact_email' => 'contact@shopifystore1.com',
            'contact_phone' => '+1-555-1001',
            'whatsapp_number' => '+1-555-1002',
            'facebook_url' => 'https://facebook.com/shopifystore1',
            'instagram_url' => 'https://instagram.com/shopifystore1',
            'twitter_url' => '',
            'youtube_url' => '',
            'tiktok_url' => '',
            'pinterest_url' => '',
            'facebook_ads_count' => 5,
        ],
        [
            'domain' => 'etsystore2.com',
            'title' => 'Etsy Handmade Crafts',
            'description' => 'Handmade crafts and unique gifts on Etsy',
            'language' => 'en',
            'country' => 'UK',
            'currency' => 'GBP',
            'product_count' => 80,
            'avg_price' => 15.00,
            'categories' => 'Crafts, Gifts',
            'tech_stack' => 'Etsy',
            'shipping_destinations' => 'UK, EU',
            'payment_methods' => 'PayPal, Direct Debit',
            'contact_email' => 'contact@etsystore2.com',
            'contact_phone' => '+44-20-7123-4567',
            'whatsapp_number' => '',
            'facebook_url' => '',
            'instagram_url' => 'https://instagram.com/etsycrafts',
            'twitter_url' => '',
            'youtube_url' => '',
            'tiktok_url' => '',
            'pinterest_url' => 'https://pinterest.com/etsycrafts',
            'facebook_ads_count' => 2,
        ],
        [
            'domain' => 'ebaystore3.com',
            'title' => 'eBay Electronics Outlet',
            'description' => 'Electronics and gadgets sold on eBay',
            'language' => 'en',
            'country' => 'DE',
            'currency' => 'EUR',
            'product_count' => 300,
            'avg_price' => 89.99,
            'categories' => 'Electronics, Gadgets',
            'tech_stack' => 'eBay',
            'shipping_destinations' => 'EU',
            'payment_methods' => 'PayPal',
            'contact_email' => 'contact@ebaystore3.com',
            'contact_phone' => '+49-30-9876-5432',
            'whatsapp_number' => '',
            'facebook_url' => '',
            'instagram_url' => '',
            'twitter_url' => '',
            'youtube_url' => '',
            'tiktok_url' => '',
            'pinterest_url' => '',
            'facebook_ads_count' => 8,
        ],
        [
            'domain' => 'woocommercestore4.com',
            'title' => 'WooCommerce Organic Foods',
            'description' => 'Organic food products via WooCommerce',
            'language' => 'es',
            'country' => 'ES',
            'currency' => 'EUR',
            'product_count' => 120,
            'avg_price' => 12.50,
            'categories' => 'Food, Organic',
            'tech_stack' => 'WooCommerce',
            'shipping_destinations' => 'ES',
            'payment_methods' => 'Bank Transfer, Credit Card',
            'contact_email' => 'contact@woocommercestore4.com',
            'contact_phone' => '+34-91-2345-6789',
            'whatsapp_number' => '+34-600-123-456',
            'facebook_url' => 'https://facebook.com/organicfoods',
            'instagram_url' => 'https://instagram.com/organicfoods',
            'twitter_url' => '',
            'youtube_url' => '',
            'tiktok_url' => '',
            'pinterest_url' => '',
            'facebook_ads_count' => 3,
        ],
        [
            'domain' => 'squarestore5.com',
            'title' => 'Square Boutique',
            'description' => 'Fashion boutique using Square Online',
            'language' => 'fr',
            'country' => 'CA',
            'currency' => 'CAD',
            'product_count' => 90,
            'avg_price' => 55.00,
            'categories' => 'Apparel, Fashion',
            'tech_stack' => 'Square',
            'shipping_destinations' => 'CA, US',
            'payment_methods' => 'Square Pay, Credit Card',
            'contact_email' => 'contact@squarestore5.com',
            'contact_phone' => '+1-604-555-9000',
            'whatsapp_number' => '',
            'facebook_url' => 'https://facebook.com/squareboutique',
            'instagram_url' => 'https://instagram.com/squareboutique',
            'twitter_url' => '',
            'youtube_url' => '',
            'tiktok_url' => '',
            'pinterest_url' => '',
            'facebook_ads_count' => 6,
        ]
    ];

    foreach ($mockStores as $store) {
        $stmt = $pdo->prepare("
            INSERT INTO stores (
                domain, title, description, language, country, currency, 
                product_count, avg_price, categories, tech_stack, 
                shipping_destinations, payment_methods, contact_email, 
                contact_phone, whatsapp_number, facebook_url, instagram_url, 
                twitter_url, youtube_url, tiktok_url, pinterest_url, facebook_ads_count
            ) VALUES (
                :domain, :title, :description, :language, :country, :currency, 
                :product_count, :avg_price, :categories, :tech_stack, 
                :shipping_destinations, :payment_methods, :contact_email, 
                :contact_phone, :whatsapp_number, :facebook_url, :instagram_url, 
                :twitter_url, :youtube_url, :tiktok_url, :pinterest_url, :facebook_ads_count
            )
        ");

        $stmt->execute([
            ':domain' => $store['domain'],
            ':title' => $store['title'],
            ':description' => $store['description'],
            ':language' => $store['language'],
            ':country' => $store['country'],
            ':currency' => $store['currency'],
            ':product_count' => $store['product_count'],
            ':avg_price' => $store['avg_price'],
            ':categories' => $store['categories'],
            ':tech_stack' => $store['tech_stack'],
            ':shipping_destinations' => $store['shipping_destinations'],
            ':payment_methods' => $store['payment_methods'],
            ':contact_email' => $store['contact_email'],
            ':contact_phone' => $store['contact_phone'],
            ':whatsapp_number' => $store['whatsapp_number'],
            ':facebook_url' => $store['facebook_url'],
            ':instagram_url' => $store['instagram_url'],
            ':twitter_url' => $store['twitter_url'],
            ':youtube_url' => $store['youtube_url'],
            ':tiktok_url' => $store['tiktok_url'],
            ':pinterest_url' => $store['pinterest_url'],
            ':facebook_ads_count' => $store['facebook_ads_count'],
        ]);
        echo "Inserted: " . $store['title'] . "\n";
    }
    echo "Mock data insertion complete.\n";
} else {
    echo "Mock data insertion skipped (USE_MOCK_DATA is false).\n";
} 